<?php

namespace ContainerLxk7a3O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C8RZrZnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C8RZrZn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C8RZrZn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\InscriptionController::index' => ['privates', '.service_locator.1d_X9dd', 'get_ServiceLocator_1dX9ddService', true],
            'App\\Controller\\ProfilController::index' => ['privates', '.service_locator.8iLZ8sJ', 'get_ServiceLocator_8iLZ8sJService', true],
            'App\\Controller\\ProfilController::settings' => ['privates', '.service_locator.uX47yds', 'get_ServiceLocator_UX47ydsService', true],
            'App\\Controller\\RegistrationController::oubliPass' => ['privates', '.service_locator.GfClzYs', 'get_ServiceLocator_GfClzYsService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\RegistrationController::resetPassword' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\InscriptionController:index' => ['privates', '.service_locator.1d_X9dd', 'get_ServiceLocator_1dX9ddService', true],
            'App\\Controller\\ProfilController:index' => ['privates', '.service_locator.8iLZ8sJ', 'get_ServiceLocator_8iLZ8sJService', true],
            'App\\Controller\\ProfilController:settings' => ['privates', '.service_locator.uX47yds', 'get_ServiceLocator_UX47ydsService', true],
            'App\\Controller\\RegistrationController:oubliPass' => ['privates', '.service_locator.GfClzYs', 'get_ServiceLocator_GfClzYsService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\RegistrationController:resetPassword' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\InscriptionController::index' => '?',
            'App\\Controller\\ProfilController::index' => '?',
            'App\\Controller\\ProfilController::settings' => '?',
            'App\\Controller\\RegistrationController::oubliPass' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::resetPassword' => '?',
            'App\\Controller\\UserController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\InscriptionController:index' => '?',
            'App\\Controller\\ProfilController:index' => '?',
            'App\\Controller\\ProfilController:settings' => '?',
            'App\\Controller\\RegistrationController:oubliPass' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:resetPassword' => '?',
            'App\\Controller\\UserController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
