<?php

namespace ContainerLxk7a3O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8iLZ8sJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8iLZ8sJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8iLZ8sJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['privates', 'App\\Services\\UploadFileManager', 'getUploadFileManagerService', true],
        ], [
            'manager' => 'App\\Services\\UploadFileManager',
        ]);
    }
}
