<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH7ftB3P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7ftB3P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7ftB3P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH7ftB3P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH7ftB3P\App_KernelDevDebugContainer([
    'container.build_hash' => 'H7ftB3P',
    'container.build_id' => '6f2f5e28',
    'container.build_time' => 1608237302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7ftB3P');
