<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxk7a3O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxk7a3O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLxk7a3O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLxk7a3O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLxk7a3O\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lxk7a3O',
    'container.build_id' => 'd9cae890',
    'container.build_time' => 1608065187,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxk7a3O');
