<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPRBDsHH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPRBDsHH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPRBDsHH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPRBDsHH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPRBDsHH\App_KernelDevDebugContainer([
    'container.build_hash' => 'PRBDsHH',
    'container.build_id' => 'a5af53c9',
    'container.build_time' => 1608230429,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPRBDsHH');
